### ISSUE TITLE
Add to Maven Repository

### ISSUE THREAD

**Issue by adamfisher** [icann/czds-api-client-java#4]
A quick search of the Maven repository does not show any packages for this SDK. Can this please be added there so we can easily import it into our projects?

https://mvnrepository.com/search?q=czds
https://search.maven.org/search?q=czds-client

**Comment by dongmei-cao** [comment]
@adamfisher Here is the artifact in Maven Central Repository:


<dependency>
    <groupId>org.icann.czds</groupId>
    <artifactId>czds-client</artifactId>
    <version>1.0</version>
</dependency>
