### ISSUE TITLE
release timeline?

### ISSUE THREAD

**Issue by maxcellent** [icann/czds-api-client-java#7]
Hi, this may not be the best idea to raise an issue but there is no contact on the readme.md

Wondering when will be the next release? Our project requires jackson-databind version to be at least 2.10.0.  I can see in the latest codebase is already using 2.10.1 but from maven central it's still using 2.9.x: 
https://repo1.maven.org/maven2/org/icann/czds/czds-client/1.0/czds-client-1.0.pom

Do you think you can help to release a new version with the latest dependency?

**Comment by dongmei-cao** [comment]
@maxcellent  Version 1.0.3 has been released with jackson-databind  2.10.1 and java 11. Please checkout out. Thanks.

**Comment by maxcellent** [comment]
thanks, this is working fine now.
