### ISSUE TITLE
probem on .com zone with api client java

### ISSUE THREAD

**Issue by iptwins** [icann/czds-api-client-java#9]
Hi,
we are an ICANN accredited registrar, and we regularly download zonefiles from the ICANN website with this java api client.

But we have a problem, since 8 March the JAVA script blocks on the .COM zone, we have the following error on a Linux system:

**Start download zone file(s). This may take a while.
Downloading zone file from https://czds-api.icann.org/czds/downloads/com.zone
Saving zone file to com.txt.gz
ERROR: Failed to save file to /xxxxx/czds-api-client-java/target/zonefiles/com.txt.gz**

Would you have any idea how to solve this problem ? I haven't found anything to get around the problem.
no problem for the rest of the zonefiles, i guess the .COM has become too big and is a problem for the JAVA script.

thanks in advance for your help.

**Comment by chandrawisnu** [comment]
> Hi,
> we are an ICANN accredited registrar, and we regularly download zonefiles from the ICANN website with this java api client.
> 
> But we have a problem, since 8 March the JAVA script blocks on the .COM zone, we have the following error on a Linux system:
> 
> **Start download zone file(s). This may take a while. Downloading zone file from https://czds-api.icann.org/czds/downloads/com.zone Saving zone file to com.txt.gz ERROR: Failed to save file to /xxxxx/czds-api-client-java/target/zonefiles/com.txt.gz**
> 
> Would you have any idea how to solve this problem ? I haven't found anything to get around the problem.
> no problem for the rest of the zonefiles, i guess the .COM has become too big and is a problem for the JAVA script.
> 
> thanks in advance for your help.

**Comment by iptwins** [comment]
Hi, 
we managed to get around the problem.
To do this, you need to use a machine with enough RAM and then the .com will work.
We used to use a machine with a small amount of memory, which worked fine, but it doesn't work anymore.
